<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Component;
use Webmozart\Assert\Assert;

/**
 * ComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Component $object
     */
    public function add($object){
        Assert::isInstanceOf($object, Component::class);

        $this->getEntityManager()->persist($object);
        $this->getEntityManager()->flush();
    }
}
