imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        charset: UTF8
        path: '%database_path%'

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
